### ISSUE TITLE
TypeError: object of type 'generator' has no len()

### ISSUE THREAD

**Issue by chikurin66** [Hironsan/asari#11]
When I tried to run it, I got the following error.

```
>>> sonar.ping(text="広告多すぎる")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/asari/api.py", line 27, in ping
    vector = self.preprocessor.transform([text])
  File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 1880, in transform
    X = super().transform(raw_documents)
  File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 1250, in transform
    _, X = self._count_vocab(raw_documents, fixed_vocab=True)
  File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 1110, in _count_vocab
    for feature in analyze(doc):
  File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 111, in _analyze
    doc = ngrams(doc)
  File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 242, in _word_ngrams
    n_original_tokens = len(original_tokens)
TypeError: object of type 'generator' has no len()
```

**Comment by andrenguyensha** [comment]
> When I tried to run it, I got the following error.
> 
> ```
> >>> sonar.ping(text="広告多すぎる")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.8/site-packages/asari/api.py", line 27, in ping
>     vector = self.preprocessor.transform([text])
>   File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 1880, in transform
>     X = super().transform(raw_documents)
>   File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 1250, in transform
>     _, X = self._count_vocab(raw_documents, fixed_vocab=True)
>   File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 1110, in _count_vocab
>     for feature in analyze(doc):
>   File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 111, in _analyze
>     doc = ngrams(doc)
>   File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 242, in _word_ngrams
>     n_original_tokens = len(original_tokens)
> TypeError: object of type 'generator' has no len()
> ```

uninstall Janome 0.4.1 and install Janome 0.3.7 by using pip install "Janome == 0.3.7"

**Comment by AbhiPawar5** [comment]
Thank you @andrenguyensha . It worked for me!
